import {useEffect,useMemo,useState,type FormEvent} from 'react'
import {Modal} from '../components/AdminLayout'
import {PageTop} from '../components/CommerceUi'
import {money} from '../data/admin-utils'
import {deactivatePromotion,getPromotionHistory,getPromotions,getPromotionStats,savePromotion,type Promotion,type PromotionHistory,type PromotionStats} from '../services/admin-finance'

export default function Promotions(){
 const [items,setItems]=useState<Promotion[]>([]),[stats,setStats]=useState<PromotionStats>(),[history,setHistory]=useState<PromotionHistory[]>([]),[query,setQuery]=useState(''),[status,setStatus]=useState(''),[editing,setEditing]=useState<Partial<Promotion>|null>(null),[error,setError]=useState('')
 const load=()=>Promise.all([getPromotions(),getPromotionStats(),getPromotionHistory()]).then(([a,b,c])=>{setItems(a);setStats(b);setHistory(c);setError('')}).catch(e=>setError(e.message))
 useEffect(()=>{load()},[])
 const shown=useMemo(()=>items.filter(x=>(!status||x.TrangThai===status)&&`${x.MaKhuyenMai} ${x.TenKhuyenMai}`.toLowerCase().includes(query.toLowerCase())),[items,status,query])
 const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const d=new FormData(e.currentTarget);try{await savePromotion({KhuyenMaiID:editing?.KhuyenMaiID,MaKhuyenMai:String(d.get('code')).trim(),TenKhuyenMai:String(d.get('name')).trim(),PhanTramGiam:Number(d.get('percent')),SoTienGiam:Number(d.get('amount')),NgayBatDau:String(d.get('from'))+' 00:00:00',NgayKetThuc:String(d.get('to'))+' 23:59:59',DieuKien:String(d.get('condition')).trim()||null,TrangThai:String(d.get('status')) as Promotion['TrangThai']});setEditing(null);load()}catch(e){setError((e as Error).message)}}
 return <div className="admin-page commerce-page finance-admin-page promotions-admin-page"><PageTop trail="MARKETING › KHUYẾN MÃI" title="QUẢN LÝ KHUYẾN MÃI" actions={<button className="primary" onClick={()=>setEditing({TrangThai:'ACTIVE',PhanTramGiam:0,SoTienGiam:0})}>＋ TẠO KHUYẾN MÃI</button>} metrics={[
  ['SỐ CHƯƠNG TRÌNH',String(stats?.SoChuongTrinh||0),'Trong cơ sở dữ liệu'],['ĐANG ACTIVE',String(stats?.DangActive||0),'Đúng thời gian hiệu lực'],['LƯỢT SỬ DỤNG',String(stats?.LuotSuDung||0),'Gói tập + Shop + PT'],['TỔNG GIẢM GIÁ',money(Number(stats?.TongSoTienGiam||0)),'Từ lịch sử áp dụng']]}/>
  <div className="commerce-filters finance-filters"><div className="commerce-fields"><input placeholder="Mã hoặc tên khuyến mãi" value={query} onChange={e=>setQuery(e.target.value)}/><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">Tất cả trạng thái</option><option>ACTIVE</option><option>INACTIVE</option><option>EXPIRED</option></select></div></div>{error&&<p className="empty">{error}</p>}
  <section className="commerce-card promotion-list-card"><header className="panel-heading"><div><span>CHƯƠNG TRÌNH</span><h2>Danh sách khuyến mãi</h2></div><b>{shown.length} chương trình</b></header><div className="commerce-table-wrap"><table className="commerce-table promotion-table"><thead><tr><th>MÃ / TÊN</th><th className="numeric">MỨC GIẢM</th><th>THỜI GIAN</th><th>TRẠNG THÁI</th><th className="numeric">SỬ DỤNG</th><th>THAO TÁC</th></tr></thead><tbody>{shown.map(x=><tr key={x.KhuyenMaiID}><td><b className="promotion-code">{x.MaKhuyenMai}</b><small>{x.TenKhuyenMai}</small></td><td className="numeric promotion-discount-value">{Number(x.PhanTramGiam)>0?`${x.PhanTramGiam}%`:money(Number(x.SoTienGiam))}</td><td><span className="date-range">{new Date(x.NgayBatDau).toLocaleDateString('vi-VN')}<i>→</i>{new Date(x.NgayKetThuc).toLocaleDateString('vi-VN')}</span></td><td><span className={`status-badge status-${x.TrangThai.toLowerCase()}`}>{x.TrangThai}</span></td><td className="numeric"><b>{x.LuotSuDung} lượt</b><small>{money(Number(x.TongSoTienGiam))}</small></td><td className="row-actions"><button onClick={()=>setEditing(x)}>Sửa</button><button disabled={x.TrangThai==='INACTIVE'} onClick={async()=>{await deactivatePromotion(x.KhuyenMaiID);load()}}>Ngừng</button></td></tr>)}</tbody></table>{!shown.length&&<p className="empty">Không có chương trình phù hợp.</p>}</div></section>
  <section className="commerce-card promotion-history-card"><header className="panel-heading"><div><span>HOẠT ĐỘNG</span><h2>Lịch sử sử dụng tổng hợp</h2></div><b>{history.length} lượt</b></header><div className="commerce-table-wrap"><table className="commerce-table history-table"><thead><tr><th>THỜI GIAN</th><th>MÃ</th><th>NGUỒN</th><th>THAM CHIẾU</th><th className="numeric">GIẢM</th></tr></thead><tbody>{history.map(x=><tr key={`${x.Loai}-${x.ApDungKhuyenMaiID}`}><td>{new Date(x.NgayApDung).toLocaleString('vi-VN')}</td><td><b className="promotion-code">{x.MaKhuyenMai}</b></td><td><span className="method-chip">{x.Loai}</span></td><td>#{x.ThamChieuID}</td><td className="numeric amount-cell">{money(Number(x.SoTienGiam))}</td></tr>)}</tbody></table></div><p className="capability-note">Voucher gói tập đang được hỗ trợ. Shop/PT chỉ xuất hiện khi có bản ghi áp dụng thật trong DB.</p></section>
  {editing&&<Modal title={editing.KhuyenMaiID?'SỬA KHUYẾN MÃI':'TẠO KHUYẾN MÃI'} onClose={()=>setEditing(null)}><form className="promotion-form" onSubmit={submit}><div className="form-grid"><label>Mã khuyến mãi<input name="code" required defaultValue={editing.MaKhuyenMai}/></label><label>Tên chương trình<input name="name" required defaultValue={editing.TenKhuyenMai}/></label><fieldset><legend>Mức giảm</legend><label>Phần trăm giảm<input name="percent" type="number" min="0" max="100" step="0.01" defaultValue={editing.PhanTramGiam}/></label><label>Số tiền giảm<input name="amount" type="number" min="0" step="0.01" defaultValue={editing.SoTienGiam}/></label></fieldset><fieldset><legend>Thời gian áp dụng</legend><label>Từ ngày<input name="from" type="date" required defaultValue={editing.NgayBatDau?.slice(0,10)}/></label><label>Đến ngày<input name="to" type="date" required defaultValue={editing.NgayKetThuc?.slice(0,10)}/></label></fieldset><label>Trạng thái<select name="status" defaultValue={editing.TrangThai}><option>ACTIVE</option><option>INACTIVE</option><option>EXPIRED</option></select></label><label>Điều kiện<input name="condition" defaultValue={editing.DieuKien||''}/></label></div><footer className="modal-actions"><button type="button" onClick={()=>setEditing(null)}>Hủy</button><button className="primary">Lưu thay đổi</button></footer></form></Modal>}
 </div>
}
