import {useEffect,useState} from 'react'
import {money} from '../data/admin-utils'
import {getReport,type Report} from '../services/admin-finance'

const ymd=(d:Date)=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`
const range=(days:number)=>{const to=new Date(),from=new Date();from.setDate(to.getDate()-days+1);return[ymd(from),ymd(to)]}
const n=(v:unknown)=>Number(v||0)
function Table({title,heads,rows}:{title:string;heads:string[];rows:(string|number)[][]}){return <article className="report-card"><h2>{title}</h2><div className="commerce-table-wrap"><table className="commerce-table"><thead><tr>{heads.map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{rows.map((row,i)=><tr key={i}>{row.map((x,j)=><td key={j}>{x}</td>)}</tr>)}</tbody></table>{!rows.length&&<p className="empty">Chưa có dữ liệu trong kỳ.</p>}</div></article>}
export default function Reports(){
 const initial=range(7),[from,setFrom]=useState(initial[0]),[to,setTo]=useState(initial[1]),[data,setData]=useState<Report>(),[error,setError]=useState('')
 useEffect(()=>{if(from>to){setError('Khoảng ngày không hợp lệ');return}getReport(from,to).then(x=>{setData(x);setError('')}).catch(e=>setError(e.message))},[from,to])
 const preset=(kind:'today'|'week'|'month')=>{const now=new Date();if(kind==='today'){const x=ymd(now);setFrom(x);setTo(x)}else if(kind==='week'){const [a,b]=range(7);setFrom(a);setTo(b)}else{setFrom(ymd(new Date(now.getFullYear(),now.getMonth(),1)));setTo(ymd(now))}}
 return <div className="reports-page commerce-page"><header className="report-heading"><div><span><i/> DỮ LIỆU CƠ SỞ DỮ LIỆU</span><h1>BÁO CÁO & THỐNG KÊ</h1><p>Doanh thu chỉ lấy giao dịch ThanhToan có trạng thái SUCCESS.</p></div><div className="report-actions"><nav><button onClick={()=>preset('today')}>Hôm nay</button><button onClick={()=>preset('week')}>7 ngày</button><button onClick={()=>preset('month')}>Tháng này</button></nav><label>Từ <input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>Đến <input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label></div></header>{error&&<p className="empty">{error}</p>}{data&&<>
  <section className="report-summary">{[['TỔNG DOANH THU',money(n(data.revenue.total)),'SUCCESS'],['GÓI TẬP',money(n(data.revenue.package)),'Thanh toán gói'],['SHOP',money(n(data.revenue.shop)),'Thanh toán đơn hàng'],['PT','Chưa có dữ liệu','Chưa có thanh toán PT']].map(([a,b,c])=><article key={a}><header><span>{a}</span></header><strong>{b}</strong><footer><span>{c}</span></footer></article>)}</section>
  <section className="report-main"><Table title="DOANH THU THEO NGÀY" heads={['Ngày','Doanh thu']} rows={data.revenueByDay.map(x=>[new Date(x.date).toLocaleDateString('vi-VN'),money(n(x.amount))])}/><Table title="THEO PHƯƠNG THỨC" heads={['Phương thức','Doanh thu']} rows={data.revenueByMethod.map(x=>[x.method,money(n(x.amount))])}/></section>
  <section className="report-main"><Table title="HỘI VIÊN" heads={['Chỉ số','Số lượng']} rows={[["Tổng",n(data.members.total)],["ACTIVE",n(data.members.active)],["Mới trong kỳ",n(data.members.newMembers)],["Đăng ký gói mới",n(data.members.newRegistrations)],["Sắp hết hạn",n(data.members.expiring)],["Hết hạn",n(data.members.expired)]]}/><Table title="CHECK-IN" heads={['Chỉ số','Số lượt']} rows={[["Tổng lượt",n(data.checkins.total)],["CHECKED_IN",n(data.checkins.checkedIn)],["CHECKED_OUT",n(data.checkins.checkedOut)],...[...data.peakHours].map(x=>[`Khung ${x.hour}:00`,n(x.count)])]}/></section>
  <section className="report-main"><Table title="SHOP" heads={['Chỉ số','Giá trị']} rows={[["Số đơn",n(data.shop.total)],["COMPLETED",n(data.shop.completed)],["CANCELLED",n(data.shop.cancelled)],["Doanh thu SUCCESS",money(n(data.shop.revenue))],...data.topProducts.map(x=>[x.TenSanPham,n(x.quantity)])]}/><Table title="PT" heads={['Chỉ số','Số lượt']} rows={[["Số lượt thuê",n(data.pt.total)],["PENDING",n(data.pt.pending)],["CONFIRMED",n(data.pt.confirmed)],["COMPLETED",n(data.pt.completed)],["CANCELLED",n(data.pt.cancelled)],...data.topTrainers.map(x=>[x.HoTen,n(x.rentals)])]}/></section>
  <Table title="CHECK-IN THEO NGÀY" heads={['Ngày','Lượt']} rows={data.checkinsByDay.map(x=>[new Date(x.date).toLocaleDateString('vi-VN'),n(x.count)])}/>
 </>}</div>
}
