import { useMemo, useState, type FormEvent } from "react";
import { MetricCard, Modal } from "../components/AdminLayout";
import { trainers } from "../data/trainers.mock";
import { trainerShifts as seed, type TrainerShift, type ShiftType } from "../data/trainer-roster.mock";

const hours=Array.from({length:17},(_,i)=>`${String(i+6).padStart(2,"0")}:00`),typeLabel:Record<ShiftType,string>={pt:"PT 1-1",floor_duty:"Trực sàn",available:"Slot trống",leave:"Nghỉ phép",break:"Nghỉ trưa"};
export default function TrainerRosterPage(){
 const [items,setItems]=useState(seed),[view,setView]=useState("week"),[week,setWeek]=useState(0),[branch,setBranch]=useState("all"),[specialty,setSpecialty]=useState("all"),[modal,setModal]=useState<"add"|"detail"|"auto"|null>(null),[selected,setSelected]=useState<TrainerShift|null>(null),[toast,setToast]=useState(""),[requests,setRequests]=useState(["Đổi ca Trần Hoàng Nam ↔ Lê Khắc Huy","Nghỉ phép Đặng Quốc Minh"]);
 const notify=(s:string)=>{setToast(s);setTimeout(()=>setToast(""),1800)},visible=useMemo(()=>items.filter(x=>branch==="all"||x.branch===branch),[items,branch]);
 const add=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const d=new FormData(e.currentTarget),coach=trainers.find(x=>x.id===Number(d.get("trainer")))!,id=Date.now();setItems([...items,{id,trainerId:coach.id,trainerName:coach.name,trainerLevel:coach.level,date:String(d.get("date")),startTime:String(d.get("start")),endTime:String(d.get("end")),type:d.get("type") as ShiftType,activity:String(d.get("area")),status:"confirmed",branch:String(d.get("branch"))}]);setModal(null);notify("Đã thêm ca làm việc")};
 const auto=()=>{setModal("auto");setTimeout(()=>{setItems(xs=>[...xs,{id:Date.now(),trainerId:5,trainerName:"Trần Mai Anh",trainerLevel:"Pro Trainer",date:"2026-09-18",startTime:"18:00",endTime:"20:00",type:"floor_duty",activity:"Ca tự động · Cardio",status:"confirmed",branch:"Vincom Q.1"}]);setModal(null);notify("Đã mô phỏng xếp ca tự động")},1200)};
 const open=(s:TrainerShift)=>{setSelected(s);setModal("detail")};
 return <div className="admin-page pt-page"><header className="page-heading"><div><p>VẬN HÀNH CHÍNH　›　HLV & LỊCH TẬP PT　›　<b>LỊCH LÀM VIỆC & PHÂN CA HLV</b></p><h1>LỊCH LÀM VIỆC & PHÂN CA HUẤN LUYỆN VIÊN (ROSTER)</h1></div><div className="heading-actions"><button onClick={auto}>✦ Xếp ca tự động (AI Auto-Schedule)</button><button className="primary" onClick={()=>setModal("add")}>＋ Thêm ca làm việc / Đăng ký trực ca</button></div></header>
 <section className="roster-metrics"><MetricCard label="CA SÁNG (06:00 - 14:00)" value="14" note="HLV trực sàn / 48 ca PT 1-1" tone="mint"/><MetricCard label="CA CHIỀU / TỐI PEAK" value="28" note="HLV trực sàn / 108 ca PT 1-1"/><MetricCard label="ĐỘ PHỦ PHÂN CA" value="100%" note="0 trống lịch · SLA đạt chuẩn" tone="mint"/></section>
 <section className="roster-controls"><div><button onClick={()=>setWeek(week-1)}>‹ Tuần trước</button><b>Tuần hiện tại {week?`(${week>0?"+":""}${week})`:""}</b><button onClick={()=>setWeek(week+1)}>Tuần sau ›</button><button onClick={()=>setWeek(0)}>Hôm nay</button></div><div className="view-tabs">{[["day","Ngày"],["week","Tuần"],["month","Tháng"]].map(([k,v])=><button className={view===k?"active":""} onClick={()=>setView(k)} key={k}>Xem theo {v}</button>)}</div><div><select value={branch} onChange={e=>setBranch(e.target.value)}><option value="all">Tất cả cơ sở</option>{[...new Set(items.map(x=>x.branch))].map(x=><option key={x}>{x}</option>)}</select><select value={specialty} onChange={e=>setSpecialty(e.target.value)}><option value="all">Tất cả cụm bộ môn</option><option>Strength</option><option>Pilates</option></select><button onClick={()=>notify("Đã áp dụng bộ lọc nâng cao")}>☰ Bộ lọc nâng cao</button></div></section>
 <div className="roster-legend">CHÚ THÍCH CA: {Object.entries(typeLabel).map(([k,v])=><span className={k} key={k}>■ {v}</span>)}</div><section className="timeline-wrap"><div className="timeline-head"><b>HUẤN LUYỆN VIÊN</b>{hours.map(h=><span key={h}>{h}</span>)}</div>{trainers.slice(0,5).map(t=><div className="timeline-row" key={t.id}><div className="person"><i>{t.avatar}</i><span><b>{t.name}</b><small>{t.level}</small></span></div><div className="timeline-track">{hours.map(h=><span key={h}/>) }{visible.filter(s=>s.trainerId===t.id).map(s=>{const start=Number(s.startTime.slice(0,2))-6,end=Number(s.endTime.slice(0,2))-6;return <button className={`shift ${s.type}`} style={{left:`${start/17*100}%`,width:`${Math.max(1,end-start)/17*100}%`}} onClick={()=>open(s)} key={s.id}><b>{s.memberName||typeLabel[s.type]}</b><small>{s.activity}</small></button>})}<button className="empty-slot" onClick={()=>setModal("add")}>＋ Nhận đặt ca</button></div></div>)}</section>
 <section className="requests pt-panel"><header><div><h2>ĐƠN ĐỔI CA TRỰC & NGHỈ PHÉP TRỰC TUYẾN</h2><small>{requests.length} yêu cầu chờ duyệt</small></div></header><div>{requests.map((r,i)=><article key={r}><h3>{r}</h3><p>{i?"Ngày xin nghỉ: Thứ Sáu · Đã ký bàn giao":"Xin hoán đổi ca sáng sang ca chiều · Không xung đột"}</p><footer><button onClick={()=>{setRequests(requests.filter(x=>x!==r));notify("Đã từ chối yêu cầu")}}>Từ chối</button><button className="primary" onClick={()=>{setRequests(requests.filter(x=>x!==r));notify(i?"Đã duyệt phép & bàn giao":"Đã duyệt hoán đổi")}}>{i?"Duyệt phép & Bàn giao":"Duyệt hoán đổi"}</button></footer></article>)}</div></section>
 {modal==="add"&&<Modal title="THÊM CA LÀM VIỆC" onClose={()=>setModal(null)}><form onSubmit={add}><div className="form-grid"><label>HLV<select name="trainer">{trainers.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select></label><label>Ngày<input name="date" type="date" required/></label><label>Bắt đầu<input name="start" type="time" required/></label><label>Kết thúc<input name="end" type="time" required/></label><label>Loại ca<select name="type">{Object.entries(typeLabel).map(([k,v])=><option value={k} key={k}>{v}</option>)}</select></label><label>Cơ sở<select name="branch"><option>Vincom Q.1</option><option>Thảo Điền Hub</option><option>Crescent Elite Q.7</option></select></label><label>Khu vực<input name="area" required/></label></div><footer className="modal-actions"><button type="button" onClick={()=>setModal(null)}>Hủy</button><button className="primary">Thêm ca</button></footer></form></Modal>}
 {modal==="detail"&&selected&&<Modal title="CHI TIẾT CA LÀM VIỆC" onClose={()=>setModal(null)}><div className="detail-list"><div><span>HLV</span><b>{selected.trainerName}</b></div><div><span>Thời gian</span><b>{selected.startTime} – {selected.endTime}</b></div><div><span>Loại ca</span><b>{typeLabel[selected.type]}</b></div><div><span>Nội dung</span><b>{selected.memberName||selected.activity}</b></div><div><span>Trạng thái</span><b>{selected.status}</b></div></div></Modal>}{modal==="auto"&&<Modal title="XẾP CA TỰ ĐỘNG" onClose={()=>setModal(null)}><div className="auto-loading">◌<p>Đang mô phỏng tối ưu lịch HLV...</p></div></Modal>}{toast&&<div className="toast">✓ {toast}</div>}</div>
}
