import Ionicons from '@expo/vector-icons/Ionicons';
import { router, useLocalSearchParams } from 'expo-router';
import { useCallback, useEffect, useRef, useState } from 'react';
import { Image, Modal, Pressable, ScrollView, Share, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { getPackageById, type PackageClass } from '@/constants/package-detail';
import { AuthColors as C } from '@/constants/theme';
import { useAuth } from '@/context/AuthContext';
import { addCalendarMonths, diamondDurations, formatVND, localDate, periodLabel } from '@/lib/package-logic';
import { createEnrollment, getFavorite, setFavorite, type MembershipEnrollment } from '@/lib/membership';

function Icon({ name, color = C.lime, size = 19 }: { name: keyof typeof Ionicons.glyphMap; color?: string; size?: number }) { return <Ionicons name={name} size={size} color={color} />; }
function SectionHeading({ title, badge }: { title: string; badge?: string }) { return <View style={s.sectionHeading}><Text style={s.sectionTitle}>{title}</Text>{badge ? <Text style={s.sectionBadge}>{badge}</Text> : null}</View>; }
function Action({ title, onPress, muted = false, disabled = false }: { title: string; onPress: () => void; muted?: boolean; disabled?: boolean }) { return <Pressable onPress={onPress} disabled={disabled} style={[s.action, muted && s.actionMuted, disabled && { opacity: .55 }]}><Text style={[s.actionText, muted && { color: C.text }]}>{title}</Text><Icon name="arrow-forward" color={muted ? C.text : '#283500'} size={19} /></Pressable>; }

export default function PackageDetailScreen() {
  const { id } = useLocalSearchParams<{ id?: string }>();
  const item = getPackageById(typeof id === 'string' ? id : '');
  const { user } = useAuth();
  const [selectedMonths, setSelectedMonths] = useState(12);
  const [favorite, setFavoriteState] = useState(false);
  const [toast, setToast] = useState('');
  const [enrollOpen, setEnrollOpen] = useState(false);
  const [created, setCreated] = useState<MembershipEnrollment | null>(null);
  const [selectedClass, setSelectedClass] = useState<PackageClass | null>(null);
  const [submitting, setSubmitting] = useState(false);
  const submittingRef = useRef(false);
  const toastTimer = useRef<ReturnType<typeof setTimeout> | null>(null);
  const packageId = item?.id;
  useEffect(() => { if (!packageId) return; let active = true; getFavorite(packageId).then(value => { if (active) setFavoriteState(value); }).catch(() => { if (active) setToast('Không thể tải mục yêu thích.'); }); return () => { active = false; }; }, [packageId]);
  useEffect(() => () => { if (toastTimer.current) clearTimeout(toastTimer.current); }, []);
  const showToast = useCallback((message: string) => { setToast(message); if (toastTimer.current) clearTimeout(toastTimer.current); toastTimer.current = setTimeout(() => setToast(''), 2500); }, []);
  const back = () => router.canGoBack() ? router.back() : router.replace('/packages');
  if (!item) return <SafeAreaView style={s.safe}><View style={s.header}><Pressable onPress={back}><Icon name="arrow-back" color={C.text} /></Pressable><Text style={s.headerTitle}>CHI TIẾT GÓI TẬP</Text></View><View style={s.notFound}><Text style={s.title}>Không tìm thấy gói tập</Text><Action title="VỀ GÓI TẬP" onPress={() => router.replace('/packages')} /></View></SafeAreaView>;
  const option = diamondDurations.find(x => x.months === selectedMonths)!;
  const starts = new Date();
  const expires = addCalendarMonths(starts, option.months + option.bonusMonths);
  async function toggleFavorite() {
    const next = !favorite;
    try { await setFavorite(item!.id, next); setFavoriteState(next); showToast(next ? 'Đã lưu gói Diamond All-Access vào danh sách yêu thích!' : 'Đã bỏ lưu gói tập.'); }
    catch { showToast('Không thể lưu mục yêu thích.'); }
  }
  async function sharePackage() {
    try { await Share.share({ title: `${item!.name} | QA-Gym`, message: `${item!.name} | QA-Gym\n${option.months} tháng${option.bonusMonths ? ` + ${option.bonusMonths} tháng tặng` : ''}\n${formatVND(option.monthlyPrice)}/tháng\nTổng ${formatVND(option.totalPrice)}` }); }
    catch { showToast('Không thể mở chia sẻ trên thiết bị này.'); }
  }
  async function confirmEnrollment() {
    if (submittingRef.current || !user) return;
    submittingRef.current = true;
    setSubmitting(true);
    try { const row = await createEnrollment(user.email, item!.id, item!.name, option); setCreated(row); setEnrollOpen(false); }
    catch { showToast('Không thể lưu đăng ký. Vui lòng thử lại.'); }
    finally { submittingRef.current = false; setSubmitting(false); }
  }
  return <SafeAreaView style={s.safe} edges={['top', 'bottom']}>
    <View style={s.header}><Pressable onPress={back} accessibilityLabel="Quay lại Gói tập" hitSlop={12}><Icon name="arrow-back" color={C.text} size={22} /></Pressable><Text style={s.headerTitle}>EXERCISE DETAIL</Text><View style={s.headerRight}><Pressable accessibilityLabel="Trợ giúp" onPress={() => showToast('Lễ tân QA-Gym: 1900 8899')}><Icon name="help-circle-outline" color={C.muted} size={19} /></Pressable><Pressable accessibilityLabel="Hồ sơ" onPress={() => router.push('/profile')} style={s.avatar}><Icon name="person-outline" color="#283500" size={17} /></Pressable></View></View>
    <ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={s.content}>
      <View style={s.micro}><View style={s.microLeft}><View style={s.dot} /><Text style={s.microText}>ĐANG ÁP DỤNG ƯU ĐÃI HÈ 2025</Text></View><View style={s.microActions}><Pressable onPress={toggleFavorite} accessibilityLabel="Yêu thích" accessibilityState={{ selected: favorite }} style={s.roundIcon}><Icon name={favorite ? 'heart' : 'heart-outline'} color={favorite ? C.lime : C.text} size={20} /></Pressable><Pressable onPress={sharePackage} accessibilityLabel="Chia sẻ" style={s.roundIcon}><Icon name="share-social-outline" color={C.text} size={19} /></Pressable></View></View>
      <View style={s.heroCard}><View style={s.heroTop}><View style={s.bestBadge}><Icon name="star-outline" color="#283500" size={12} /><Text style={s.bestText}>BEST SELLER & TOÀN DIỆN NHẤT</Text></View><View style={s.diamondIcon}><Icon name="diamond-outline" color={C.lime} /></View></View><Text style={s.heroKicker}>{item.tier}</Text><Text style={s.heroTitle}>{item.name}</Text><Text style={s.heroDescription}>{item.description}</Text><View style={s.heroImageWrap}><Image source={item.hero} style={s.heroImage} resizeMode="cover" /><View style={s.imageShade} /><View style={s.imageBadges}><Text style={s.imagePill}>◉ Mở cửa 24/7</Text><Text style={s.imagePill}>⌖ 14 Chi nhánh</Text></View></View><View style={s.priceBox}><View style={s.priceRow}><Text style={s.price}>{formatVND(option.monthlyPrice)}</Text><Text style={s.perMonth}>/ THÁNG</Text></View><View style={s.priceMeta}><Text style={s.original}>{formatVND(option.originalMonthlyPrice)}</Text><Text style={s.discount}>{option.discountLabel}</Text></View></View><View style={s.durationHead}><Text style={s.tinyLabel}>THỜI HẠN ĐÓNG GÓI</Text><Text style={s.tinyAccent}>◉ Giá ưu đãi cam kết</Text></View><View style={s.durationRow}>{diamondDurations.map(duration => <Pressable key={duration.months} onPress={() => setSelectedMonths(duration.months)} style={[s.duration, option.months === duration.months && s.durationActive]}><Text style={[s.durationTitle, option.months === duration.months && s.durationTextActive]}>{duration.months} Tháng</Text><Text style={[s.durationSubtitle, option.months === duration.months && s.durationTextActive]}>{duration.subtitle}</Text>{'badge' in duration && <Text style={s.hotDeal}>{duration.badge}</Text>}</Pressable>)}</View></View>
      <SectionHeading title="ĐẶC QUYỀN HỘI VIÊN DIAMOND" badge="07 Quyền lợi VIP" /><Text style={s.sectionCopy}>Trọn bộ tiện ích 5 sao độc quyền không phát sinh phụ phí.</Text>
      {item.privileges.map(privilege => <View style={s.privilege} key={privilege.id}><View style={s.privilegeIcon}><Icon name={privilege.icon as keyof typeof Ionicons.glyphMap} color={privilege.accent === 'cyan' ? C.cyan : privilege.accent === 'mint' ? C.mint : C.lime} /></View><View style={s.privilegeBody}><View style={s.privilegeTitleRow}><Text style={s.privilegeTitle}>{privilege.title}</Text><Text style={s.privilegeBadge}>{privilege.badge}</Text></View><Text style={s.privilegeCopy}>{privilege.description}</Text></View></View>)}
      <SectionHeading title="LỚP GROUP-X & YOGA ĐI KÈM" badge="100% Free" /><Text style={s.sectionCopy}>Tham gia không giới hạn số lớp mỗi ngày theo lịch đăng ký qua app.</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.classScroll}>{item.classes.map(groupClass => <Pressable key={groupClass.id} style={s.classCard} onPress={() => setSelectedClass(groupClass)}><View style={s.classImageWrap}><Image source={groupClass.image} style={s.classImage} resizeMode="cover" /><Text style={s.classTag}>{groupClass.tag}</Text></View><Text style={s.className}>{groupClass.name}</Text><Text style={s.classDescription} numberOfLines={2}>{groupClass.description}</Text><View style={s.classMetrics}><Text style={s.classMetric}>◷ {groupClass.minutes} Phút</Text><Text style={s.classKcal}>{groupClass.kcal} kcal</Text></View></Pressable>)}</ScrollView>
      <SectionHeading title="ĐÁNH GIÁ TỪ HỘI VIÊN" badge={`★ ${item.rating}`} /><Text style={s.reviewCount}>{item.reviewCount}</Text>{item.reviews.map(review => <View style={s.reviewCard} key={review.id}><View style={s.reviewHead}><Image source={review.avatar} style={s.reviewAvatar} /><View style={{ flex: 1 }}><View style={s.reviewNameRow}><Text style={s.reviewName}>{review.name}</Text><Text style={s.verified}>ĐÃ XÁC THỰC</Text></View><Text style={s.reviewDetail}>{review.detail}</Text></View><Text style={s.stars}>★★★★★</Text></View><Text style={s.reviewQuote}>{review.quote}</Text></View>)}
      <View style={s.policyCard}><View style={s.policyHeading}><Icon name="shield-checkmark-outline" /><Text style={s.policyTitle}>CAM KẾT & CHÍNH SÁCH LINH HOẠT</Text></View>{item.policies.map(policy => <View style={s.policy} key={policy.id}><Icon name={policy.icon as keyof typeof Ionicons.glyphMap} color={C.mint} size={17} /><View style={{ flex: 1 }}><Text style={s.policyName}>{policy.title}</Text><Text style={s.policyCopy}>{policy.description}</Text></View></View>)}</View>
    </ScrollView>
    {toast ? <View style={s.toast}><Text style={s.toastText}>{toast}</Text></View> : null}
    <View style={s.checkout}><View style={s.checkoutInfo}><Text style={s.checkoutLabel}>TỔNG ƯỚC TÍNH</Text><Text style={s.checkoutPrice}>{formatVND(option.totalPrice)}</Text><Text style={s.checkoutPeriod}>{periodLabel(option)}</Text></View><Pressable style={s.checkoutButton} onPress={() => setEnrollOpen(true)}><Text style={s.checkoutButtonText}>ĐĂNG KÝ NGAY</Text><Icon name="arrow-forward" color="#283500" size={17} /></Pressable></View>
    <Modal visible={enrollOpen} transparent animationType="slide" onRequestClose={() => setEnrollOpen(false)}><View style={s.modalBackdrop}><View style={s.modalCard}><Text style={s.modalKicker}>THÔNG TIN GÓI</Text><Text style={s.modalTitle}>{item.name}</Text><Summary label="Người đăng ký" value={user?.name ?? ''} /><Summary label="Thời hạn thanh toán" value={`${option.months} tháng`} /><Summary label="Thời gian sử dụng" value={`${option.months + option.bonusMonths} tháng${option.bonusMonths ? ` (tặng ${option.bonusMonths} tháng)` : ''}`} /><Summary label="Giá/tháng" value={formatVND(option.monthlyPrice)} /><Summary label="Ngày bắt đầu" value={localDate(starts)} /><Summary label="Ngày hết hạn" value={localDate(expires)} /><Summary label="Ưu đãi" value={option.discountLabel} /><View style={s.modalTotal}><Text style={s.modalTotalLabel}>TỔNG THANH TOÁN</Text><Text style={s.modalTotalPrice}>{formatVND(option.totalPrice)}</Text></View><Text style={s.modalNote}>Đơn sẽ ở trạng thái chờ thanh toán. Chưa có khoản tiền nào được thu.</Text><Action title={submitting ? 'ĐANG LƯU...' : 'XÁC NHẬN ĐĂNG KÝ'} onPress={confirmEnrollment} disabled={submitting} /><Pressable onPress={() => setEnrollOpen(false)} style={s.cancel}><Text style={s.cancelText}>HỦY</Text></Pressable></View></View></Modal>
    <Modal visible={!!created} transparent animationType="fade" onRequestClose={() => setCreated(null)}><View style={s.modalBackdrop}><View style={s.modalCard}><Icon name="checkmark-circle-outline" size={34} /><Text style={s.modalTitle}>Đăng ký đã được tạo</Text><Summary label="Mã đăng ký" value={created?.id ?? ''} /><Summary label="Gói" value={created?.packageName ?? ''} /><Summary label="Tổng tiền" value={formatVND(created?.totalPrice ?? 0)} /><Summary label="Trạng thái" value="Chờ thanh toán" /><Text style={s.modalNote}>Vui lòng thanh toán tại quầy để kích hoạt thẻ hội viên.</Text><Action title="ĐÓNG" onPress={() => setCreated(null)} /></View></View></Modal>
    <Modal visible={!!selectedClass} transparent animationType="fade" onRequestClose={() => setSelectedClass(null)}><View style={s.modalBackdrop}><View style={s.modalCard}>{selectedClass && <><Image source={selectedClass.image} style={s.modalClassImage} /><Text style={s.modalTitle}>{selectedClass.name}</Text><Text style={s.modalNote}>{selectedClass.description}</Text><Summary label="Thời lượng" value={`${selectedClass.minutes} phút`} /><Summary label="Năng lượng" value={`${selectedClass.kcal} kcal`} /></>}<Action title="ĐÓNG" onPress={() => setSelectedClass(null)} /></View></View></Modal>
  </SafeAreaView>;
}
function Summary({ label, value }: { label: string; value: string }) { return <View style={s.summary}><Text style={s.summaryLabel}>{label}</Text><Text style={s.summaryValue}>{value}</Text></View>; }
const s = StyleSheet.create({
  safe: { flex: 1, backgroundColor: C.background }, header: { minHeight: 52, paddingHorizontal: 16, flexDirection: 'row', alignItems: 'center', gap: 14, borderBottomWidth: 1, borderBottomColor: C.surfaceLow }, headerTitle: { color: C.text, fontSize: 13, fontWeight: '800', flex: 1 }, headerRight: { flexDirection: 'row', alignItems: 'center', gap: 13 }, avatar: { width: 29, height: 29, borderRadius: 15, backgroundColor: C.text, alignItems: 'center', justifyContent: 'center' }, content: { width: '100%', maxWidth: 540, alignSelf: 'center', paddingHorizontal: 16, paddingBottom: 32 }, micro: { height: 62, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, microLeft: { flexDirection: 'row', alignItems: 'center', gap: 5, flex: 1 }, dot: { width: 7, height: 7, borderRadius: 4, backgroundColor: C.lime }, microText: { color: C.lime, fontSize: 9, fontWeight: '800', letterSpacing: .3 }, microActions: { flexDirection: 'row', gap: 8 }, roundIcon: { width: 36, height: 36, borderRadius: 18, backgroundColor: C.surfaceHigh, alignItems: 'center', justifyContent: 'center' },
  heroCard: { backgroundColor: '#222a22', borderRadius: 16, padding: 15, marginBottom: 25 }, heroTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, bestBadge: { backgroundColor: C.lime, flexDirection: 'row', alignItems: 'center', gap: 4, borderRadius: 20, paddingHorizontal: 9, paddingVertical: 5 }, bestText: { color: '#283500', fontSize: 9, fontWeight: '900', letterSpacing: .7 }, diamondIcon: { width: 32, height: 32, borderRadius: 16, alignItems: 'center', justifyContent: 'center', backgroundColor: C.surfaceHigh }, heroKicker: { color: C.muted, fontSize: 10, fontWeight: '800', letterSpacing: 1, marginTop: 15 }, heroTitle: { color: C.text, fontSize: 26, lineHeight: 31, fontWeight: '800', marginTop: 3 }, heroDescription: { color: C.muted, fontSize: 13, lineHeight: 19, marginTop: 4, marginBottom: 15 }, heroImageWrap: { height: 160, borderRadius: 11, overflow: 'hidden', backgroundColor: C.surfaceLowest }, heroImage: { width: '100%', height: '100%' }, imageShade: { position: 'absolute', bottom: 0, left: 0, right: 0, height: 48, backgroundColor: 'rgba(12,14,17,.68)' }, imageBadges: { position: 'absolute', bottom: 8, left: 9, flexDirection: 'row', gap: 6 }, imagePill: { color: C.lime, backgroundColor: '#151916', fontSize: 10, fontWeight: '700', paddingHorizontal: 8, paddingVertical: 5, borderRadius: 12, overflow: 'hidden' }, priceBox: { backgroundColor: C.surfaceLowest, borderRadius: 11, padding: 13, marginTop: 15 }, priceRow: { flexDirection: 'row', alignItems: 'baseline', flexWrap: 'wrap', gap: 5 }, price: { color: C.lime, fontSize: 31, lineHeight: 37, fontWeight: '900', letterSpacing: -1 }, perMonth: { color: C.muted, fontSize: 11, fontWeight: '800' }, priceMeta: { flexDirection: 'row', alignItems: 'center', gap: 10 }, original: { color: '#8e9379', fontSize: 12, textDecorationLine: 'line-through' }, discount: { color: C.lime, backgroundColor: '#303b0d', borderRadius: 12, overflow: 'hidden', paddingHorizontal: 8, paddingVertical: 3, fontSize: 10, fontWeight: '700' }, durationHead: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 14, marginBottom: 7, gap: 6 }, tinyLabel: { color: C.muted, fontSize: 10, fontWeight: '800' }, tinyAccent: { color: C.mint, fontSize: 10, fontWeight: '700' }, durationRow: { flexDirection: 'row', gap: 7 }, duration: { flex: 1, minWidth: 0, backgroundColor: C.surface, borderRadius: 9, minHeight: 64, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 2 }, durationActive: { backgroundColor: C.lime }, durationTitle: { color: C.text, fontSize: 14, fontWeight: '800' }, durationSubtitle: { color: C.muted, fontSize: 10, marginTop: 3, textAlign: 'center' }, durationTextActive: { color: '#283500' }, hotDeal: { position: 'absolute', top: 2, right: 2, color: C.lime, backgroundColor: '#333538', fontSize: 8, fontWeight: '800', paddingHorizontal: 5, paddingVertical: 2, borderRadius: 3, overflow: 'hidden' },
  sectionHeading: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: 3, gap: 8 }, sectionTitle: { color: C.text, fontSize: 15, fontWeight: '800', flexShrink: 1 }, sectionBadge: { color: C.lime, fontSize: 10, fontWeight: '800' }, sectionCopy: { color: C.muted, fontSize: 12, lineHeight: 17, marginTop: 6, marginBottom: 12 }, privilege: { flexDirection: 'row', gap: 11, padding: 11, backgroundColor: C.surface, borderRadius: 10, marginBottom: 8 }, privilegeIcon: { width: 33, height: 33, borderRadius: 8, backgroundColor: C.surfaceHigh, alignItems: 'center', justifyContent: 'center' }, privilegeBody: { flex: 1 }, privilegeTitleRow: { flexDirection: 'row', justifyContent: 'space-between', gap: 5 }, privilegeTitle: { color: C.text, fontSize: 12, fontWeight: '800', flex: 1 }, privilegeBadge: { color: C.lime, fontSize: 9, fontWeight: '800', maxWidth: 88, textAlign: 'right' }, privilegeCopy: { color: C.muted, fontSize: 11, lineHeight: 15, marginTop: 4 }, classScroll: { gap: 10, paddingBottom: 24 }, classCard: { width: 186, backgroundColor: C.surface, borderRadius: 11, overflow: 'hidden', paddingBottom: 10 }, classImageWrap: { height: 102 }, classImage: { width: '100%', height: '100%' }, classTag: { position: 'absolute', left: 7, top: 7, color: C.lime, backgroundColor: '#111916', fontSize: 9, fontWeight: '800', paddingHorizontal: 5, paddingVertical: 3, overflow: 'hidden' }, className: { color: C.text, fontSize: 13, fontWeight: '800', marginTop: 8, marginHorizontal: 9 }, classDescription: { color: C.muted, fontSize: 10, lineHeight: 14, height: 28, marginTop: 3, marginHorizontal: 9 }, classMetrics: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 9, marginHorizontal: 9 }, classMetric: { color: C.muted, fontSize: 10 }, classKcal: { color: C.lime, fontSize: 10, fontWeight: '800' },
  reviewCount: { color: C.muted, fontSize: 10, marginBottom: 10 }, reviewCard: { backgroundColor: C.surface, borderRadius: 10, padding: 12, marginBottom: 9 }, reviewHead: { flexDirection: 'row', alignItems: 'center', gap: 9 }, reviewAvatar: { width: 34, height: 34, borderRadius: 17 }, reviewNameRow: { flexDirection: 'row', alignItems: 'center', gap: 6 }, reviewName: { color: C.text, fontSize: 12, fontWeight: '800' }, verified: { color: '#283500', backgroundColor: C.lime, borderRadius: 3, overflow: 'hidden', fontSize: 7, fontWeight: '900', paddingHorizontal: 4, paddingVertical: 2 }, reviewDetail: { color: C.muted, fontSize: 10, marginTop: 3 }, stars: { color: C.lime, fontSize: 11 }, reviewQuote: { color: C.text, fontSize: 11, lineHeight: 16, marginTop: 9 }, policyCard: { backgroundColor: C.surfaceLow, borderRadius: 12, padding: 13, marginTop: 8 }, policyHeading: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 11 }, policyTitle: { color: C.text, fontSize: 13, fontWeight: '800' }, policy: { flexDirection: 'row', gap: 10, marginBottom: 11 }, policyName: { color: C.text, fontSize: 11, fontWeight: '800' }, policyCopy: { color: C.muted, fontSize: 10, lineHeight: 15, marginTop: 3 },
  checkout: { backgroundColor: '#0c0e11', borderTopWidth: 1, borderTopColor: C.surfaceHigh, paddingHorizontal: 16, paddingVertical: 11, flexDirection: 'row', alignItems: 'center', gap: 12 }, checkoutInfo: { flex: 1 }, checkoutLabel: { color: C.muted, fontSize: 9, fontWeight: '800' }, checkoutPrice: { color: C.lime, fontSize: 19, fontWeight: '900' }, checkoutPeriod: { color: C.muted, fontSize: 10, marginTop: 2 }, checkoutButton: { backgroundColor: C.lime, borderRadius: 10, minHeight: 47, paddingHorizontal: 12, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 5 }, checkoutButtonText: { color: '#283500', fontSize: 11, fontWeight: '800' }, toast: { position: 'absolute', bottom: 92, alignSelf: 'center', maxWidth: '90%', backgroundColor: C.surfaceHigh, borderWidth: 1, borderColor: C.border, paddingHorizontal: 15, paddingVertical: 10, borderRadius: 12, zIndex: 5 }, toastText: { color: C.text, fontSize: 12, textAlign: 'center' },
  modalBackdrop: { flex: 1, backgroundColor: 'rgba(0,0,0,.7)', justifyContent: 'flex-end' }, modalCard: { backgroundColor: C.surfaceLow, borderTopLeftRadius: 20, borderTopRightRadius: 20, padding: 20, paddingBottom: 28, maxHeight: '90%' }, modalKicker: { color: C.lime, fontSize: 10, fontWeight: '800', letterSpacing: 1 }, modalTitle: { color: C.text, fontSize: 21, fontWeight: '800', marginTop: 5, marginBottom: 13 }, summary: { flexDirection: 'row', justifyContent: 'space-between', gap: 9, paddingVertical: 7, borderBottomWidth: 1, borderBottomColor: C.surfaceHigh }, summaryLabel: { color: C.muted, fontSize: 12, flex: 1 }, summaryValue: { color: C.text, fontSize: 12, fontWeight: '700', flex: 1, textAlign: 'right' }, modalTotal: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 13, alignItems: 'center' }, modalTotalLabel: { color: C.muted, fontSize: 11, fontWeight: '800' }, modalTotalPrice: { color: C.lime, fontSize: 20, fontWeight: '900' }, modalNote: { color: C.muted, fontSize: 12, lineHeight: 18, marginTop: 14 }, action: { backgroundColor: C.lime, borderRadius: 10, minHeight: 48, alignItems: 'center', justifyContent: 'center', flexDirection: 'row', gap: 8, marginTop: 19 }, actionMuted: { backgroundColor: C.surfaceHigh }, actionText: { color: '#283500', fontSize: 12, fontWeight: '800' }, cancel: { alignItems: 'center', padding: 13 }, cancelText: { color: C.muted, fontSize: 12, fontWeight: '700' }, modalClassImage: { height: 170, width: '100%', borderRadius: 10 }, notFound: { flex: 1, justifyContent: 'center', padding: 24 }, title: { color: C.text, fontSize: 22, fontWeight: '800' },
});
