import { FontAwesome } from '@expo/vector-icons';
import { router } from 'expo-router';
import { useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';

type Transaction = { icon: string; title: string; code: string; date: string; amount: string; detail: string; points: string; status: string; statusType: 'success' | 'refund' };

const transactions: Transaction[] = [
  { icon: 'shopping-bag', title: 'Đơn hàng dinh dưỡng', code: '#QA-ORD-88219', date: '15/06/2026 • 09:20', amount: '-2.875.000đ', detail: 'Rule1 Whey Protein, C4 Pre-Workout, Bình lắc QA...', points: '+2.850 QA-Points', status: 'Đã giao thành công', statusType: 'success' },
  { icon: 'bolt', title: 'Đăng ký gói hội viên', code: '#PT-BOOK-1409', date: '03/06/2026 • 14:15', amount: '-9.100.000đ', detail: 'Gói Chuyên Hóa 24 Buổi • 1-1 cùng HLV Trần Hoàng...', points: '+9.100 QA-Points', status: 'Đã kích hoạt hợp đồng', statusType: 'success' },
  { icon: 'diamond', title: 'Gia hạn Gói tập Diamond', code: '#PKG-DIA-89922', date: '28/05/2026 • 09:00', amount: '-10.490.000đ', detail: 'Thẻ hội viên Diamond 12 Tháng (+2 tháng tặng kèm)', points: '+1.050 QA-Points', status: 'Thành công', statusType: 'success' },
  { icon: 'shopping-bag', title: 'Mua sắm phụ kiện gym', code: '#SHOP-POS-10044', date: '14/05/2026 • 19:40', amount: '-650.000đ', detail: 'Bình lắc inox 800ml & Găng tay Gym Pro Grip', points: 'POS Terminal #02', status: 'Thành công', statusType: 'success' },
  { icon: 'money', title: 'Hoàn tiền đơn hàng', code: '#REF-ORD-65122', date: '18/04/2026 • 11:20', amount: '+420.000đ', detail: 'Dây kháng lực PowerBand Heavy (Hủy do đổi địa chỉ...)', points: 'Đã trả toàn', status: 'Đã hoàn tiền', statusType: 'refund' },
];

export default function TransactionHistoryScreen() {
  const [month, setMonth] = useState('Tất cả (12)');
  return <View style={styles.container}>
    <SafeAreaView edges={['top', 'bottom']} style={styles.safeArea}>
      <ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.content}>
        <View style={styles.header}><Pressable style={styles.iconButton} onPress={() => router.back()} accessibilityLabel="Quay lại"><FontAwesome name="angle-left" size={21} color="#edf2e8" /></Pressable><Text style={styles.headerTitle}>TRANSACTION HISTORY</Text><View style={styles.account}><FontAwesome name="user" size={11} color="#516000" /></View></View>
        <View style={styles.intro}><View><Text style={styles.introTitle}>HÓA ĐƠN & THANH TOÁN</Text><Text style={styles.introDetail}>Hóa đơn tổng tập, PT & phụ kiện Pro Shop</Text></View><View style={styles.exportBadge}><FontAwesome name="download" size={9} color="#d9ff00" /><Text style={styles.exportText}>XUẤT FILE</Text></View></View>
        <View style={styles.stats}><Stat label="CHI TIÊU NĂM 2026" value="23.265.000đ" /><Stat label="ĐIỂM TÍCH LŨY" value="+1.475 Pts" accent /></View>
        <View style={styles.monthHeader}><Text style={styles.monthTitle}><FontAwesome name="calendar" size={10} color="#d9ff00" /> Năm 2026 (Tất cả các tháng)</Text><FontAwesome name="sliders" size={12} color="#b7c500" /></View>
        <View style={styles.months}><MonthButton label="TẤT CẢ (12)" active={month === 'Tất cả (12)'} onPress={() => setMonth('Tất cả (12)')} /><MonthButton label="GÓI TẬP & HỘI VIÊN (2)" active={month === 'Gói'} onPress={() => setMonth('Gói')} /><MonthButton label="THỂ HỮU ÍCH (2)" active={month === 'Thể'} onPress={() => setMonth('Thể')} /></View>
        <View style={styles.monthLabel}><Text style={styles.monthLabelText}>● THÁNG 06 / 2026</Text><Text style={styles.monthTotal}>Tổng chi: 11.975.000đ</Text></View>
        {transactions.slice(0, 2).map((transaction) => <TransactionCard transaction={transaction} key={transaction.code} />)}
        <View style={styles.monthLabel}><Text style={styles.monthLabelText}>● THÁNG 05 / 2026</Text><Text style={styles.monthTotal}>Tổng chi: 11.140.000đ</Text></View>
        {transactions.slice(2, 4).map((transaction) => <TransactionCard transaction={transaction} key={transaction.code} />)}
        <View style={styles.monthLabel}><Text style={styles.monthLabelText}>● THÁNG 04 / 2026</Text><Text style={styles.refundTotal}>+420.000đ hoàn về</Text></View>
        <TransactionCard transaction={transactions[4]} />
        <Pressable style={styles.downloadButton} accessibilityLabel="Tải toàn bộ sao kê giao dịch"><FontAwesome name="download" size={12} color="#182000" /><Text style={styles.downloadText}>TẢI TOÀN BỘ SAO KÊ GIAO DỊCH PDF (2026)</Text></Pressable>
        <View style={styles.note}><FontAwesome name="question-circle" size={14} color="#d9ff00" /><View style={styles.noteCopy}><Text style={styles.noteTitle}>Cần xuất hóa đơn VAT cho Doanh Nghiệp?</Text><Text style={styles.noteDetail}>Hóa đơn điện tử VAT hợp lệ sẽ được gửi về email công ty trong 24h làm việc.</Text><Text style={styles.noteLink}>YÊU CẦU XUẤT HÓA ĐƠN NGAY →</Text></View></View>
      </ScrollView>
    </SafeAreaView>
  </View>;
}

function Stat({ label, value, accent = false }: { label: string; value: string; accent?: boolean }) { return <View style={styles.stat}><Text style={styles.statLabel}>{label}</Text><Text style={[styles.statValue, accent && styles.accent]}>{value}</Text><Text style={styles.statHint}>⌁ Hạng Hội viên: Diamond</Text></View>; }
function MonthButton({ label, active, onPress }: { label: string; active: boolean; onPress: () => void }) { return <Pressable style={[styles.monthButton, active && styles.monthActive]} onPress={onPress}><Text style={[styles.monthButtonText, active && styles.monthActiveText]}>{label}</Text></Pressable>; }
function TransactionCard({ transaction }: { transaction: Transaction }) { return <View style={styles.transactionCard}><View style={styles.transactionTop}><View style={styles.transactionIcon}><FontAwesome name={transaction.icon as never} size={12} color="#d9ff00" /></View><View style={styles.transactionHeading}><Text style={styles.transactionTitle}>{transaction.title}</Text><Text style={styles.transactionCode}>{transaction.code} • {transaction.date}</Text></View><Text style={[styles.transactionAmount, transaction.statusType === 'refund' && styles.refundAmount]}>{transaction.amount}</Text></View><View style={styles.transactionBody}><Text style={styles.bodyText}>▣ {transaction.detail}</Text><Text style={styles.points}>{transaction.points}</Text></View><View style={styles.transactionBottom}><Text style={[styles.transactionStatus, transaction.statusType === 'refund' && styles.refundStatus]}><FontAwesome name={transaction.statusType === 'refund' ? 'check-circle' : 'check-circle'} size={9} color={transaction.statusType === 'refund' ? '#56dda8' : '#d9ff00'} /> {transaction.status}</Text><Pressable style={styles.detailButton}><FontAwesome name="file-text" size={9} color="#d9ff00" /><Text style={styles.detailText}>{transaction.statusType === 'refund' ? 'CHI TIẾT HOÀN TẤT' : 'XEM HÓA ĐƠN VAT'}</Text></Pressable></View></View>; }

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#0d1011' }, safeArea: { flex: 1, width: '100%', maxWidth: 540, alignSelf: 'center' }, content: { paddingHorizontal: 10, paddingBottom: 28 },
  header: { height: 43, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, iconButton: { width: 31, height: 31, borderRadius: 9, backgroundColor: '#242829', alignItems: 'center', justifyContent: 'center' }, headerTitle: { color: '#e9f0e5', fontSize: 9, fontWeight: '900' }, account: { width: 25, height: 25, borderRadius: 13, backgroundColor: '#edf5dc', alignItems: 'center', justifyContent: 'center' },
  intro: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingVertical: 8 }, introTitle: { color: '#f0f5eb', fontSize: 10, fontWeight: '900' }, introDetail: { color: '#919c91', fontSize: 7, marginTop: 3 }, exportBadge: { flexDirection: 'row', alignItems: 'center', gap: 5, backgroundColor: '#252d25', padding: 7, borderRadius: 5 }, exportText: { color: '#d9ff00', fontSize: 6, fontWeight: '900' }, stats: { flexDirection: 'row', gap: 7 }, stat: { flex: 1, backgroundColor: '#1b2022', borderRadius: 7, padding: 9 }, statLabel: { color: '#8b968d', fontSize: 6, fontWeight: '900' }, statValue: { color: '#f0f5eb', fontSize: 13, fontWeight: '900', marginTop: 5 }, accent: { color: '#d9ff00' }, statHint: { color: '#43d59e', fontSize: 6, marginTop: 4 },
  monthHeader: { height: 31, borderRadius: 6, backgroundColor: '#1b2022', marginTop: 10, paddingHorizontal: 9, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, monthTitle: { color: '#e6eee2', fontSize: 7, fontWeight: '900' }, months: { flexDirection: 'row', gap: 5, paddingVertical: 8 }, monthButton: { minHeight: 25, borderRadius: 12, backgroundColor: '#1b2022', paddingHorizontal: 9, justifyContent: 'center' }, monthActive: { backgroundColor: '#caff00' }, monthButtonText: { color: '#aab5aa', fontSize: 6, fontWeight: '900' }, monthActiveText: { color: '#182000' }, monthLabel: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 5, marginBottom: 6 }, monthLabelText: { color: '#d9ff00', fontSize: 7, fontWeight: '900' }, monthTotal: { color: '#929d92', fontSize: 6 }, refundTotal: { color: '#55dca8', fontSize: 6, fontWeight: '900' },
  transactionCard: { backgroundColor: '#1b2022', borderRadius: 8, padding: 9, marginBottom: 8 }, transactionTop: { flexDirection: 'row', alignItems: 'center' }, transactionIcon: { width: 28, height: 28, borderRadius: 7, backgroundColor: '#304216', alignItems: 'center', justifyContent: 'center', marginRight: 8 }, transactionHeading: { flex: 1 }, transactionTitle: { color: '#e7eee4', fontSize: 9, fontWeight: '900' }, transactionCode: { color: '#8b968c', fontSize: 6, marginTop: 3 }, transactionAmount: { color: '#eff5e9', fontSize: 11, fontWeight: '900' }, refundAmount: { color: '#54dda8' }, transactionBody: { backgroundColor: '#171c1d', borderRadius: 5, padding: 7, marginTop: 7 }, bodyText: { color: '#d2dbd0', fontSize: 7 }, points: { color: '#d9ff00', fontSize: 6, fontWeight: '900', marginTop: 4, textAlign: 'right' }, transactionBottom: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: 7 }, transactionStatus: { color: '#47d69e', fontSize: 6, fontWeight: '900' }, refundStatus: { color: '#56dda8' }, detailButton: { backgroundColor: '#303538', borderRadius: 5, paddingHorizontal: 8, paddingVertical: 6, flexDirection: 'row', alignItems: 'center', gap: 5 }, detailText: { color: '#d9ff00', fontSize: 6, fontWeight: '900' }, downloadButton: { minHeight: 37, borderRadius: 7, backgroundColor: '#caff00', marginTop: 10, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 7 }, downloadText: { color: '#182000', fontSize: 8, fontWeight: '900' }, note: { flexDirection: 'row', backgroundColor: '#1b2022', borderRadius: 7, padding: 9, marginTop: 8 }, noteCopy: { flex: 1, marginLeft: 8 }, noteTitle: { color: '#e6eee2', fontSize: 8, fontWeight: '900' }, noteDetail: { color: '#8d988e', fontSize: 7, lineHeight: 10, marginTop: 4 }, noteLink: { color: '#d9ff00', fontSize: 6, fontWeight: '900', marginTop: 5 },
});
