CREATE DATABASE IF NOT EXISTS gym_management

USE gym_management;

CREATE TABLE TaiKhoan (
    TaiKhoanID INT AUTO_INCREMENT PRIMARY KEY,
    Email VARCHAR(100) NOT NULL UNIQUE,
    MatKhau VARCHAR(255) NOT NULL,
    VaiTro ENUM('CUSTOMER', 'STAFF', 'ADMIN') NOT NULL DEFAULT 'CUSTOMER',
    TrangThai ENUM('ACTIVE', 'LOCKED') NOT NULL DEFAULT 'ACTIVE',
    NgayTao DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE HoiVien (
    HoiVienID INT AUTO_INCREMENT PRIMARY KEY,
    TaiKhoanID INT NOT NULL UNIQUE,
    HoTen VARCHAR(100) NOT NULL,
    NgaySinh DATE NULL,
    GioiTinh ENUM('NAM', 'NU', 'KHAC') NULL,
    SoDienThoai VARCHAR(20) NULL,
    Email VARCHAR(100) NULL,
    DiaChi VARCHAR(255) NULL,
    AnhDaiDien VARCHAR(255) NULL,
    NgayDangKy DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    TrangThai ENUM('ACTIVE', 'INACTIVE', 'BLOCKED') NOT NULL DEFAULT 'ACTIVE',

    CONSTRAINT FK_HoiVien_TaiKhoan
        FOREIGN KEY (TaiKhoanID)
        REFERENCES TaiKhoan(TaiKhoanID)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

CREATE TABLE NhanVien (
    NhanVienID INT AUTO_INCREMENT PRIMARY KEY,
    TaiKhoanID INT NOT NULL UNIQUE,
    HoTen VARCHAR(100) NOT NULL,
    NgaySinh DATE NULL,
    GioiTinh ENUM('NAM', 'NU', 'KHAC') NULL,
    SoDienThoai VARCHAR(20) NULL,
    Email VARCHAR(100) NULL,
    ChucVu VARCHAR(100) NULL,
    NgayVaoLam DATE NULL,
    TrangThai ENUM('ACTIVE', 'INACTIVE', 'BLOCKED') NOT NULL DEFAULT 'ACTIVE',

    CONSTRAINT FK_NhanVien_TaiKhoan
        FOREIGN KEY (TaiKhoanID)
        REFERENCES TaiKhoan(TaiKhoanID)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

CREATE TABLE GoiTap (
    GoiTapID INT AUTO_INCREMENT PRIMARY KEY,
    TenGoi VARCHAR(100) NOT NULL,
    MoTa TEXT NULL,
    ThoiHan INT NOT NULL COMMENT 'Số ngày sử dụng',
    Gia DECIMAL(15,2) NOT NULL DEFAULT 0,
    TrangThai ENUM('ACTIVE', 'INACTIVE') NOT NULL DEFAULT 'ACTIVE',
    NgayTao DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE DangKyGoiTap (
    DangKyID INT AUTO_INCREMENT PRIMARY KEY,
    HoiVienID INT NOT NULL,
    GoiTapID INT NOT NULL,
    NgayDangKy DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    NgayBatDau DATE NOT NULL,
    NgayKetThuc DATE NOT NULL,
    GiaThanhToan DECIMAL(15,2) NOT NULL DEFAULT 0,
    TrangThai ENUM('PENDING', 'ACTIVE', 'EXPIRED', 'CANCELLED') 
        NOT NULL DEFAULT 'PENDING',

    CONSTRAINT FK_DangKyGoiTap_HoiVien
        FOREIGN KEY (HoiVienID)
        REFERENCES HoiVien(HoiVienID)
        ON DELETE RESTRICT
        ON UPDATE CASCADE,

    CONSTRAINT FK_DangKyGoiTap_GoiTap
        FOREIGN KEY (GoiTapID)
        REFERENCES GoiTap(GoiTapID)
        ON DELETE RESTRICT
        ON UPDATE CASCADE
);

CREATE TABLE MaQR (
    MaQRID INT AUTO_INCREMENT PRIMARY KEY,
    MaCode VARCHAR(255) NOT NULL UNIQUE,
    NgayTao DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    NgayHetHan DATETIME NULL,
    TrangThai ENUM('ACTIVE', 'INACTIVE', 'EXPIRED') 
        NOT NULL DEFAULT 'ACTIVE'
);

CREATE TABLE CheckIn (
    CheckInID INT AUTO_INCREMENT PRIMARY KEY,
    HoiVienID INT NOT NULL,
    MaQRID INT NOT NULL,
    ThoiGianCheckIn DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ThoiGianCheckOut DATETIME NULL,
    TrangThai ENUM('CHECKED_IN', 'CHECKED_OUT') 
        NOT NULL DEFAULT 'CHECKED_IN',

    CONSTRAINT FK_CheckIn_HoiVien
        FOREIGN KEY (HoiVienID)
        REFERENCES HoiVien(HoiVienID)
        ON DELETE RESTRICT
        ON UPDATE CASCADE,

    CONSTRAINT FK_CheckIn_MaQR
        FOREIGN KEY (MaQRID)
        REFERENCES MaQR(MaQRID)
        ON DELETE RESTRICT
        ON UPDATE CASCADE
);

CREATE TABLE PT (
    PTID INT AUTO_INCREMENT PRIMARY KEY,
    HoTen VARCHAR(100) NOT NULL,
    NgaySinh DATE NULL,
    GioiTinh ENUM('NAM', 'NU', 'KHAC') NULL,
    SoDienThoai VARCHAR(20) NULL,
    Email VARCHAR(100) NULL,
    ChuyenMon VARCHAR(255) NULL,
    KinhNghiem TEXT NULL,
    GiaThue DECIMAL(15,2) NOT NULL DEFAULT 0,
    AnhDaiDien VARCHAR(255) NULL,
    TrangThai ENUM('ACTIVE', 'INACTIVE') NOT NULL DEFAULT 'ACTIVE'
);

CREATE TABLE LichPT (
    LichPTID INT AUTO_INCREMENT PRIMARY KEY,
    PTID INT NOT NULL,
    NgayLam DATE NOT NULL,
    GioBatDau TIME NOT NULL,
    GioKetThuc TIME NOT NULL,
    TrangThai ENUM('AVAILABLE', 'BOOKED', 'OFF') 
        NOT NULL DEFAULT 'AVAILABLE',

    CONSTRAINT FK_LichPT_PT
        FOREIGN KEY (PTID)
        REFERENCES PT(PTID)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

CREATE TABLE ThuePT (
    ThuePTID INT AUTO_INCREMENT PRIMARY KEY,
    HoiVienID INT NOT NULL,
    PTID INT NOT NULL,
    LichPTID INT NOT NULL,
    NgayDat DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    GiaThue DECIMAL(15,2) NOT NULL DEFAULT 0,
    TrangThai ENUM('PENDING', 'CONFIRMED', 'COMPLETED', 'CANCELLED') 
        NOT NULL DEFAULT 'PENDING',
    GhiChu VARCHAR(500) NULL,

    CONSTRAINT FK_ThuePT_HoiVien
        FOREIGN KEY (HoiVienID)
        REFERENCES HoiVien(HoiVienID)
        ON DELETE RESTRICT
        ON UPDATE CASCADE,

    CONSTRAINT FK_ThuePT_PT
        FOREIGN KEY (PTID)
        REFERENCES PT(PTID)
        ON DELETE RESTRICT
        ON UPDATE CASCADE,

    CONSTRAINT FK_ThuePT_LichPT
        FOREIGN KEY (LichPTID)
        REFERENCES LichPT(LichPTID)
        ON DELETE RESTRICT
        ON UPDATE CASCADE
);

CREATE TABLE DanhMuc (
    DanhMucID INT AUTO_INCREMENT PRIMARY KEY,
    TenDanhMuc VARCHAR(100) NOT NULL,
    MoTa TEXT NULL,
    TrangThai ENUM('ACTIVE', 'INACTIVE') NOT NULL DEFAULT 'ACTIVE'
);

CREATE TABLE SanPham (
    SanPhamID INT AUTO_INCREMENT PRIMARY KEY,
    DanhMucID INT NOT NULL,
    TenSanPham VARCHAR(150) NOT NULL,
    MoTa TEXT NULL,
    GiaBan DECIMAL(15,2) NOT NULL DEFAULT 0,
    DonViTinh VARCHAR(30) NOT NULL DEFAULT 'Cái',
    HinhAnh VARCHAR(255) NULL,
    TrangThai ENUM('ACTIVE', 'INACTIVE', 'OUT_OF_STOCK') 
        NOT NULL DEFAULT 'ACTIVE',

    CONSTRAINT FK_SanPham_DanhMuc
        FOREIGN KEY (DanhMucID)
        REFERENCES DanhMuc(DanhMucID)
        ON DELETE RESTRICT
        ON UPDATE CASCADE
);

CREATE TABLE GioHang (
    GioHangID INT AUTO_INCREMENT PRIMARY KEY,
    HoiVienID INT NOT NULL UNIQUE,
    NgayTao DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    TrangThai ENUM('ACTIVE', 'COMPLETED') NOT NULL DEFAULT 'ACTIVE',

    CONSTRAINT FK_GioHang_HoiVien
        FOREIGN KEY (HoiVienID)
        REFERENCES HoiVien(HoiVienID)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

CREATE TABLE ChiTietGioHang (
    ChiTietGioHangID INT AUTO_INCREMENT PRIMARY KEY,
    GioHangID INT NOT NULL,
    SanPhamID INT NOT NULL,
    SoLuong INT NOT NULL DEFAULT 1,

    CONSTRAINT FK_ChiTietGioHang_GioHang
        FOREIGN KEY (GioHangID)
        REFERENCES GioHang(GioHangID)
        ON DELETE CASCADE
        ON UPDATE CASCADE,

    CONSTRAINT FK_ChiTietGioHang_SanPham
        FOREIGN KEY (SanPhamID)
        REFERENCES SanPham(SanPhamID)
        ON DELETE RESTRICT
        ON UPDATE CASCADE,

    CONSTRAINT UQ_GioHang_SanPham
        UNIQUE (GioHangID, SanPhamID)
);

CREATE TABLE DonHang (
    DonHangID INT AUTO_INCREMENT PRIMARY KEY,
    HoiVienID INT NOT NULL,
    NgayDat DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    TongTien DECIMAL(15,2) NOT NULL DEFAULT 0,
    TrangThai ENUM(
        'PENDING',
        'CONFIRMED',
        'PROCESSING',
        'COMPLETED',
        'CANCELLED'
    ) NOT NULL DEFAULT 'PENDING',
    DiaChiGiaoHang VARCHAR(255) NULL,
    GhiChu VARCHAR(500) NULL,

    CONSTRAINT FK_DonHang_HoiVien
        FOREIGN KEY (HoiVienID)
        REFERENCES HoiVien(HoiVienID)
        ON DELETE RESTRICT
        ON UPDATE CASCADE
);

CREATE TABLE ChiTietDonHang (
    ChiTietDonHangID INT AUTO_INCREMENT PRIMARY KEY,
    DonHangID INT NOT NULL,
    SanPhamID INT NOT NULL,
    SoLuong INT NOT NULL,
    DonGia DECIMAL(15,2) NOT NULL,
    ThanhTien DECIMAL(15,2) NOT NULL,

    CONSTRAINT FK_ChiTietDonHang_DonHang
        FOREIGN KEY (DonHangID)
        REFERENCES DonHang(DonHangID)
        ON DELETE CASCADE
        ON UPDATE CASCADE,

    CONSTRAINT FK_ChiTietDonHang_SanPham
        FOREIGN KEY (SanPhamID)
        REFERENCES SanPham(SanPhamID)
        ON DELETE RESTRICT
        ON UPDATE CASCADE
);

CREATE TABLE Kho (
    KhoID INT AUTO_INCREMENT PRIMARY KEY,
    TenKho VARCHAR(100) NOT NULL,
    DiaChi VARCHAR(255) NULL,
    MoTa TEXT NULL,
    TrangThai ENUM('ACTIVE', 'INACTIVE') NOT NULL DEFAULT 'ACTIVE'
);

CREATE TABLE PhieuNhap (
    PhieuNhapID INT AUTO_INCREMENT PRIMARY KEY,
    KhoID INT NOT NULL,
    NhanVienID INT NOT NULL,
    NgayNhap DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    TongTien DECIMAL(15,2) NOT NULL DEFAULT 0,
    GhiChu VARCHAR(500) NULL,
    TrangThai ENUM('PENDING', 'COMPLETED', 'CANCELLED') 
        NOT NULL DEFAULT 'PENDING',

    CONSTRAINT FK_PhieuNhap_Kho
        FOREIGN KEY (KhoID)
        REFERENCES Kho(KhoID)
        ON DELETE RESTRICT
        ON UPDATE CASCADE,

    CONSTRAINT FK_PhieuNhap_NhanVien
        FOREIGN KEY (NhanVienID)
        REFERENCES NhanVien(NhanVienID)
        ON DELETE RESTRICT
        ON UPDATE CASCADE
);

CREATE TABLE ChiTietPhieuNhap (
    ChiTietPhieuNhapID INT AUTO_INCREMENT PRIMARY KEY,
    PhieuNhapID INT NOT NULL,
    SanPhamID INT NOT NULL,
    SoLuong INT NOT NULL,
    DonGia DECIMAL(15,2) NOT NULL,
    ThanhTien DECIMAL(15,2) NOT NULL,

    CONSTRAINT FK_ChiTietPhieuNhap_PhieuNhap
        FOREIGN KEY (PhieuNhapID)
        REFERENCES PhieuNhap(PhieuNhapID)
        ON DELETE CASCADE
        ON UPDATE CASCADE,

    CONSTRAINT FK_ChiTietPhieuNhap_SanPham
        FOREIGN KEY (SanPhamID)
        REFERENCES SanPham(SanPhamID)
        ON DELETE RESTRICT
        ON UPDATE CASCADE
);

CREATE TABLE ThanhToan (
    ThanhToanID INT AUTO_INCREMENT PRIMARY KEY,
    HoiVienID INT NOT NULL,
    NhanVienID INT NULL,
    SoTien DECIMAL(15,2) NOT NULL,
    PhuongThucThanhToan ENUM(
        'TIEN_MAT',
        'CHUYEN_KHOAN',
        'THE'
    ) NOT NULL,
    NgayThanhToan DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    NoiDung VARCHAR(255) NULL,
    TrangThai ENUM('PENDING', 'SUCCESS', 'FAILED', 'CANCELLED') 
        NOT NULL DEFAULT 'PENDING',

    CONSTRAINT FK_ThanhToan_HoiVien
        FOREIGN KEY (HoiVienID)
        REFERENCES HoiVien(HoiVienID)
        ON DELETE RESTRICT
        ON UPDATE CASCADE,

    CONSTRAINT FK_ThanhToan_NhanVien
        FOREIGN KEY (NhanVienID)
        REFERENCES NhanVien(NhanVienID)
        ON DELETE SET NULL
        ON UPDATE CASCADE
);

CREATE TABLE HoaDon (
    HoaDonID INT AUTO_INCREMENT PRIMARY KEY,
    ThanhToanID INT NOT NULL UNIQUE,
    NhanVienID INT NULL,
    NgayLap DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    TongTien DECIMAL(15,2) NOT NULL DEFAULT 0,
    TrangThai ENUM('ACTIVE', 'CANCELLED') NOT NULL DEFAULT 'ACTIVE',

    CONSTRAINT FK_HoaDon_ThanhToan
        FOREIGN KEY (ThanhToanID)
        REFERENCES ThanhToan(ThanhToanID)
        ON DELETE RESTRICT
        ON UPDATE CASCADE,

    CONSTRAINT FK_HoaDon_NhanVien
        FOREIGN KEY (NhanVienID)
        REFERENCES NhanVien(NhanVienID)
        ON DELETE SET NULL
        ON UPDATE CASCADE
);

CREATE TABLE KhuyenMai (
    KhuyenMaiID INT AUTO_INCREMENT PRIMARY KEY,
    MaKhuyenMai VARCHAR(50) NOT NULL UNIQUE,
    TenKhuyenMai VARCHAR(150) NOT NULL,
    PhanTramGiam DECIMAL(5,2) NOT NULL DEFAULT 0,
    SoTienGiam DECIMAL(15,2) NOT NULL DEFAULT 0,
    NgayBatDau DATETIME NOT NULL,
    NgayKetThuc DATETIME NOT NULL,
    DieuKien TEXT NULL,
    TrangThai ENUM('ACTIVE', 'INACTIVE', 'EXPIRED') 
        NOT NULL DEFAULT 'ACTIVE'
);

CREATE TABLE ApDungKhuyenMaiDonHang (
    ApDungKhuyenMaiID INT AUTO_INCREMENT PRIMARY KEY,
    KhuyenMaiID INT NOT NULL,
    DonHangID INT NOT NULL,
    SoTienGiam DECIMAL(15,2) NOT NULL DEFAULT 0,
    NgayApDung DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT FK_ADKM_DonHang_KhuyenMai
        FOREIGN KEY (KhuyenMaiID)
        REFERENCES KhuyenMai(KhuyenMaiID)
        ON DELETE RESTRICT
        ON UPDATE CASCADE,

    CONSTRAINT FK_ADKM_DonHang_DonHang
        FOREIGN KEY (DonHangID)
        REFERENCES DonHang(DonHangID)
        ON DELETE CASCADE
        ON UPDATE CASCADE,

    CONSTRAINT UQ_ADKM_DonHang
        UNIQUE (KhuyenMaiID, DonHangID)
);

CREATE TABLE ApDungKhuyenMaiGoiTap (
    ApDungKhuyenMaiID INT AUTO_INCREMENT PRIMARY KEY,
    KhuyenMaiID INT NOT NULL,
    DangKyID INT NOT NULL,
    SoTienGiam DECIMAL(15,2) NOT NULL DEFAULT 0,
    NgayApDung DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT FK_ADKM_GoiTap_KhuyenMai
        FOREIGN KEY (KhuyenMaiID)
        REFERENCES KhuyenMai(KhuyenMaiID)
        ON DELETE RESTRICT
        ON UPDATE CASCADE,

    CONSTRAINT FK_ADKM_GoiTap_DangKy
        FOREIGN KEY (DangKyID)
        REFERENCES DangKyGoiTap(DangKyID)
        ON DELETE CASCADE
        ON UPDATE CASCADE,

    CONSTRAINT UQ_ADKM_GoiTap
        UNIQUE (KhuyenMaiID, DangKyID)
);

CREATE TABLE ApDungKhuyenMaiPT (
    ApDungKhuyenMaiID INT AUTO_INCREMENT PRIMARY KEY,
    KhuyenMaiID INT NOT NULL,
    ThuePTID INT NOT NULL,
    SoTienGiam DECIMAL(15,2) NOT NULL DEFAULT 0,
    NgayApDung DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT FK_ADKM_PT_KhuyenMai
        FOREIGN KEY (KhuyenMaiID)
        REFERENCES KhuyenMai(KhuyenMaiID)
        ON DELETE RESTRICT
        ON UPDATE CASCADE,

    CONSTRAINT FK_ADKM_PT_ThuePT
        FOREIGN KEY (ThuePTID)
        REFERENCES ThuePT(ThuePTID)
        ON DELETE CASCADE
        ON UPDATE CASCADE,

    CONSTRAINT UQ_ADKM_PT
        UNIQUE (KhuyenMaiID, ThuePTID)
);