-- Review and run manually. MySQL 8.0+.
ALTER TABLE HoiVien
  ADD COLUMN ChieuCao DECIMAL(5,2) NULL,
  ADD COLUMN CanNang DECIMAL(5,2) NULL,
  ADD COLUMN MucTieuTheHinh VARCHAR(255) NULL;

CREATE TABLE IF NOT EXISTS ThongBao (
  ThongBaoID BIGINT AUTO_INCREMENT PRIMARY KEY,
  TaiKhoanID INT NOT NULL,
  Loai VARCHAR(50) NOT NULL,
  DanhMuc VARCHAR(30) NOT NULL,
  TieuDe VARCHAR(255) NOT NULL,
  NoiDung TEXT NOT NULL,
  DoUuTien ENUM('NORMAL', 'HIGH') NOT NULL DEFAULT 'NORMAL',
  ActionType VARCHAR(50) NULL,
  ActionPayload JSON NULL,
  NgayTao DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  NgayDoc DATETIME NULL,
  INDEX IX_ThongBao_TaiKhoan_NgayTao (TaiKhoanID, NgayTao),
  CONSTRAINT FK_ThongBao_TaiKhoan FOREIGN KEY (TaiKhoanID)
    REFERENCES TaiKhoan(TaiKhoanID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS CaiDatThongBao (
  TaiKhoanID INT PRIMARY KEY,
  PushEnabled BOOLEAN NOT NULL DEFAULT FALSE,
  EmailEnabled BOOLEAN NOT NULL DEFAULT TRUE,
  SmsEnabled BOOLEAN NOT NULL DEFAULT TRUE,
  PtReminderEnabled BOOLEAN NOT NULL DEFAULT TRUE,
  PromotionEnabled BOOLEAN NOT NULL DEFAULT TRUE,
  TransactionEnabled BOOLEAN NOT NULL DEFAULT TRUE,
  SystemEnabled BOOLEAN NOT NULL DEFAULT TRUE,
  CONSTRAINT FK_CaiDatThongBao_TaiKhoan FOREIGN KEY (TaiKhoanID)
    REFERENCES TaiKhoan(TaiKhoanID) ON DELETE CASCADE
);
