export const gymEquipment = [
  {
    id: 'treadmill',
    name: 'Máy chạy bộ',
    category: 'CARDIO',
    icon: 'walk-outline',
    color: '#8cebd2',
    muscles: 'Toàn thân · Sức bền',
    description: 'Đi bộ hoặc chạy với tốc độ và độ dốc tùy chỉnh, phù hợp cho khởi động và các buổi cardio.',
  },
  {
    id: 'exercise-bike',
    name: 'Xe đạp tập',
    category: 'CARDIO',
    icon: 'bicycle-outline',
    color: '#8cebd2',
    muscles: 'Chân · Sức bền',
    description: 'Đạp xe tại chỗ với mức kháng lực điều chỉnh để luyện sức bền và vận động cơ chân.',
  },
  {
    id: 'chest-press',
    name: 'Máy đẩy ngực',
    category: 'SỨC MẠNH',
    icon: 'barbell-outline',
    color: '#d9ff00',
    muscles: 'Ngực · Vai · Tay sau',
    description: 'Tập động tác đẩy theo đường dẫn của máy, dễ lựa chọn mức tạ phù hợp với buổi tập thân trên.',
  },
  {
    id: 'lat-pulldown',
    name: 'Máy kéo xô',
    category: 'SỨC MẠNH',
    icon: 'barbell-outline',
    color: '#d9ff00',
    muscles: 'Lưng · Tay trước',
    description: 'Kéo thanh từ trên xuống để tập cơ lưng và tay trước, với mức tạ thay đổi theo khả năng.',
  },
  {
    id: 'leg-press',
    name: 'Máy đạp chân',
    category: 'SỨC MẠNH',
    icon: 'fitness-outline',
    color: '#8fb7ff',
    muscles: 'Đùi · Mông',
    description: 'Đẩy bàn đạp bằng chân từ tư thế ngồi tựa lưng, dành cho các bài tập sức mạnh thân dưới.',
  },
  {
    id: 'cable-machine',
    name: 'Máy cáp đa năng',
    category: 'ĐA NĂNG',
    icon: 'body-outline',
    color: '#8fb7ff',
    muscles: 'Ngực · Lưng · Vai · Tay',
    description: 'Thay đổi tay cầm và vị trí dây cáp để thực hiện nhiều bài kéo, đẩy và tập tay trong một khu vực.',
  },
  {
    id: 'elliptical',
    name: 'Máy trượt tuyết',
    category: 'CARDIO',
    icon: 'walk-outline',
    color: '#8cebd2',
    muscles: 'Chân · Tay · Sức bền',
    description: 'Di chuyển chân theo quỹ đạo elip kết hợp tay cầm chuyển động để tập cardio toàn thân.',
  },
  {
    id: 'stair-climber',
    name: 'Máy leo cầu thang',
    category: 'CARDIO',
    icon: 'walk-outline',
    color: '#8cebd2',
    muscles: 'Đùi · Mông · Sức bền',
    description: 'Mô phỏng bước lên cầu thang liên tục, điều chỉnh tốc độ để thay đổi cường độ buổi tập.',
  },
  {
    id: 'rowing-machine',
    name: 'Máy chèo thuyền',
    category: 'CARDIO',
    icon: 'body-outline',
    color: '#8cebd2',
    muscles: 'Chân · Lưng · Tay',
    description: 'Kết hợp đẩy chân, ngả thân và kéo tay cầm trong động tác chèo để luyện sức bền toàn thân.',
  },
  {
    id: 'ski-erg',
    name: 'Máy kéo SkiErg',
    category: 'CARDIO',
    icon: 'body-outline',
    color: '#8cebd2',
    muscles: 'Tay · Lưng · Core',
    description: 'Kéo hai tay cầm từ trên xuống như động tác trượt tuyết, kết hợp thân người để tập sức bền.',
  },
  {
    id: 'smith-machine',
    name: 'Máy Smith',
    category: 'ĐA NĂNG',
    icon: 'barbell-outline',
    color: '#8fb7ff',
    muscles: 'Chân · Mông · Ngực · Vai',
    description: 'Thanh tạ di chuyển trên ray dẫn hướng, dùng cho nhiều bài squat, đẩy ngực và đẩy vai.',
  },
  {
    id: 'hack-squat',
    name: 'Máy Hack Squat',
    category: 'SỨC MẠNH',
    icon: 'fitness-outline',
    color: '#d9ff00',
    muscles: 'Đùi trước · Mông',
    description: 'Tập squat với vai và lưng tựa vào đệm máy, di chuyển bàn trượt theo đường dẫn cố định.',
  },
  {
    id: 'leg-extension',
    name: 'Máy duỗi đùi',
    category: 'SỨC MẠNH',
    icon: 'fitness-outline',
    color: '#d9ff00',
    muscles: 'Đùi trước',
    description: 'Ngồi duỗi gối để nâng đệm chân, tập trung vào nhóm cơ đùi trước với mức tạ tùy chỉnh.',
  },
  {
    id: 'leg-curl',
    name: 'Máy cuốn đùi sau',
    category: 'SỨC MẠNH',
    icon: 'fitness-outline',
    color: '#d9ff00',
    muscles: 'Đùi sau',
    description: 'Gập gối để kéo đệm chân về phía cơ thể, bổ sung bài tập riêng cho nhóm cơ đùi sau.',
  },
  {
    id: 'calf-raise',
    name: 'Máy nhón bắp chân',
    category: 'SỨC MẠNH',
    icon: 'fitness-outline',
    color: '#d9ff00',
    muscles: 'Bắp chân',
    description: 'Nâng và hạ gót chân dưới tải trọng của máy để tập cơ bắp chân qua động tác nhón chân.',
  },
  {
    id: 'hip-abductor',
    name: 'Máy mở đùi',
    category: 'SỨC MẠNH',
    icon: 'fitness-outline',
    color: '#d9ff00',
    muscles: 'Mông · Hông ngoài',
    description: 'Ngồi đẩy hai đệm chân ra ngoài để tập nhóm cơ dạng hông và phần ngoài của cơ mông.',
  },
  {
    id: 'hip-adductor',
    name: 'Máy khép đùi',
    category: 'SỨC MẠNH',
    icon: 'fitness-outline',
    color: '#d9ff00',
    muscles: 'Đùi trong',
    description: 'Khép hai chân vào giữa để di chuyển đệm máy, tập trung vào nhóm cơ phía trong đùi.',
  },
  {
    id: 'shoulder-press',
    name: 'Máy đẩy vai',
    category: 'SỨC MẠNH',
    icon: 'barbell-outline',
    color: '#d9ff00',
    muscles: 'Vai · Tay sau',
    description: 'Ngồi đẩy tay cầm lên trên theo đường dẫn của máy để tập vai và hỗ trợ cơ tay sau.',
  },
  {
    id: 'pec-deck',
    name: 'Máy ép ngực',
    category: 'SỨC MẠNH',
    icon: 'barbell-outline',
    color: '#d9ff00',
    muscles: 'Ngực',
    description: 'Khép hai tay cầm về phía trước cơ thể theo chuyển động vòng cung để tập nhóm cơ ngực.',
  },
  {
    id: 'assisted-pull-up',
    name: 'Máy hỗ trợ hít xà',
    category: 'ĐA NĂNG',
    icon: 'body-outline',
    color: '#8fb7ff',
    muscles: 'Lưng · Tay · Ngực',
    description: 'Bệ trợ lực hỗ trợ động tác hít xà và dips; điều chỉnh mức hỗ trợ theo khả năng tập luyện.',
  },
] as const;
