import { useState } from 'react'
import type { FormEvent } from 'react'

type ForgotPasswordProps = { onBack: () => void }

export default function ForgotPassword({ onBack }: ForgotPasswordProps) {
  const [method, setMethod] = useState<'email' | 'sms'>('email')
  const [sent, setSent] = useState(false)
  const submit = (event: FormEvent) => { event.preventDefault(); setSent(true) }

  return <main className="recovery-page"><section className="recovery-shell">
    <aside className="recovery-promo"><span className="security-chip"><i /> HỆ THỐNG BẢO MẬT TÀI KHOẢN HỘI VIÊN</span><div className="recovery-copy"><div className="shield">♢</div><h1>QA-GYM <em>ACCESS KEY</em></h1><p>Bảo vệ dữ liệu luyện tập và sinh trắc học InBody, và quyền truy cập phòng tập thông minh 24/7 của bạn với giao thức mã hóa kép.</p><div className="security-stats"><article><i>◉</i><span>OTP EXPIRY<b>05:00</b><small>Tự động hủy phiên</small></span></article><article><i>♢</i><span>MÃ HÓA<b>256-BIT</b><small>Xác thực hai lớp</small></span></article></div></div><div className="club-preview"><div><b>STRENGTH / ENDURANCE FLOOR</b><strong>TRẠM TIẾP NHẬN HỘI VIÊN</strong></div><span>↗</span></div><footer className="help-desk"><i>♙</i><span>HỖ TRỢ KỸ THUẬT LỄ TÂN<b>1900 8899</b></span><strong>24/7 DESK</strong></footer></aside>
    <section className="recovery-panel"><form onSubmit={submit}><div className="recovery-steps"><span className="active"><b>1</b><i>BƯỚC 1</i>Nhập thông tin</span><span><b>2</b><i>BƯỚC 2</i>Mã OTP 6 số</span><span><b>3</b><i>BƯỚC 3</i>Đặt mật khẩu</span></div><div className="recovery-heading"><span>◉　XÁC THỰC THÀNH VIÊN</span><h2>KHÔI PHỤC MẬT KHẨU</h2><p>Vui lòng nhập Email hoặc Số điện thoại đã đăng ký với QA-Gym để nhận mã xác minh OTP đặt lại mật khẩu của bạn.</p></div><fieldset className="method-picker"><legend>PHƯƠNG THỨC TIẾP NHẬN MÃ XÁC THỰC</legend><button className={method === 'email' ? 'selected' : ''} type="button" onClick={() => setMethod('email')}>✉　Nhận qua Email</button><button className={method === 'sms' ? 'selected' : ''} type="button" onClick={() => setMethod('sms')}>▣　Nhận qua SMS</button></fieldset><label className="recovery-field">{method === 'email' ? 'ĐỊA CHỈ EMAIL HỘI VIÊN ĐÃ ĐĂNG KÝ' : 'SỐ ĐIỆN THOẠI HỘI VIÊN ĐÃ ĐĂNG KÝ'}<div><b>{method === 'email' ? '@' : '⌁'}</b><input type={method === 'email' ? 'email' : 'tel'} placeholder={method === 'email' ? 'ví dụ: member@qagym.vn' : 'ví dụ: 09xx xxx xxx'} required /></div><small>Hệ thống sẽ gửi chuỗi OTP gồm 6 chữ số tới hộp thư này.</small></label><aside className={sent ? 'recovery-alert sent' : 'recovery-alert'}><b>{sent ? '✓' : 'ⓘ'}</b><p><strong>{sent ? 'Đã gửi mã xác thực.' : 'Lưu ý an ninh:'}</strong> {sent ? 'Vui lòng kiểm tra hộp thư hoặc tin nhắn của bạn.' : 'Mã xác thực có hiệu lực trong vòng 5 phút. Nếu không nhận được mã trong thời gian này, vui lòng kiểm tra mục Thư rác (Spam) hoặc sử dụng nút Gửi lại mã.'}</p></aside><button className="send-otp" type="submit">{sent ? 'GỬI LẠI MÃ XÁC NHẬN OTP' : 'GỬI MÃ XÁC NHẬN OTP'}　➜</button><footer className="recovery-footer"><button type="button" onClick={onBack}>←　Quay lại Đăng nhập QA-Gym</button><span>●　Bảo mật thiết bị đạt chuẩn ISO 27001</span></footer></form></section>
  </section></main>
}
